# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Acer\Pyqt5-Projeler\Ödev11\Ingilizce.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ingilizce(object):
    def setupUi(self, Ingilizce):
        Ingilizce.setObjectName("Ingilizce")
        Ingilizce.resize(497, 444)
        self.centralwidget = QtWidgets.QWidget(Ingilizce)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 20, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 120, 211, 181))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(260, 120, 221, 181))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 100, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(19, 355, 461, 31))
        self.listWidget_3.setObjectName("listWidget_3")
        Ingilizce.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ingilizce)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 26))
        self.menubar.setObjectName("menubar")
        Ingilizce.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ingilizce)
        self.statusbar.setObjectName("statusbar")
        Ingilizce.setStatusBar(self.statusbar)

        self.retranslateUi(Ingilizce)
        QtCore.QMetaObject.connectSlotsByName(Ingilizce)

    def retranslateUi(self, Ingilizce):
        _translate = QtCore.QCoreApplication.translate
        Ingilizce.setWindowTitle(_translate("Ingilizce", "İngilizce Türkçe Sözlük"))
        self.pushButton.setText(_translate("Ingilizce", "Tamam"))
        self.label.setText(_translate("Ingilizce", "Sözcük"))
        self.label_2.setText(_translate("Ingilizce", "İngilizce Sözlük"))
        self.label_3.setText(_translate("Ingilizce", "Türkçe Karşılıklar"))
        self.label_4.setText(_translate("Ingilizce", "Türkçe Karşılığı"))
