# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Acer\Pyqt5-Projeler\Ödev11\Kılavuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kilavuz(object):
    def setupUi(self, Kilavuz):
        Kilavuz.setObjectName("Kilavuz")
        Kilavuz.resize(461, 125)
        self.centralwidget = QtWidgets.QWidget(Kilavuz)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 20, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 20, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        Kilavuz.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Kilavuz)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 26))
        self.menubar.setObjectName("menubar")
        Kilavuz.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Kilavuz)
        self.statusbar.setObjectName("statusbar")
        Kilavuz.setStatusBar(self.statusbar)

        self.retranslateUi(Kilavuz)
        QtCore.QMetaObject.connectSlotsByName(Kilavuz)

    def retranslateUi(self, Kilavuz):
        _translate = QtCore.QCoreApplication.translate
        Kilavuz.setWindowTitle(_translate("Kilavuz", "Türkçe Dil Kılavuzu"))
        self.pushButton.setText(_translate("Kilavuz", "Türkçe /  İngilizce"))
        self.pushButton_2.setText(_translate("Kilavuz", "İngilizce / Türkçe"))
