# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Acer\Pyqt5-Projeler\Ödev11\Turkce.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Turkce(object):
    def setupUi(self, Turkce):
        Turkce.setObjectName("Turkce")
        Turkce.resize(504, 451)
        self.centralwidget = QtWidgets.QWidget(Turkce)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 20, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 120, 211, 181))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(260, 120, 221, 181))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 100, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(17, 360, 461, 31))
        self.listWidget_3.setObjectName("listWidget_3")
        Turkce.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Turkce)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 26))
        self.menubar.setObjectName("menubar")
        Turkce.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Turkce)
        self.statusbar.setObjectName("statusbar")
        Turkce.setStatusBar(self.statusbar)

        self.retranslateUi(Turkce)
        QtCore.QMetaObject.connectSlotsByName(Turkce)

    def retranslateUi(self, Turkce):
        _translate = QtCore.QCoreApplication.translate
        Turkce.setWindowTitle(_translate("Turkce", "Türkçe İngilizce Sözlük"))
        self.pushButton.setText(_translate("Turkce", "Tamam"))
        self.label.setText(_translate("Turkce", "Sözcük"))
        self.label_2.setText(_translate("Turkce", "Türkçe Sözlük"))
        self.label_3.setText(_translate("Turkce", "İngilizce Karşılıklar"))
        self.label_4.setText(_translate("Turkce", "İngilizce Karşılığı"))
